FIND_PATH(MKL_INCLUDE_DIR mkl.h
HINTS
$ENV{MKLROOT}
PATHS
/usr/include
$ENV{HOME}/intel/mkl
PATH_SUFFIXES
mkl
)
message("$ENV{HOME} ${MKL_INCLUDE_DIR}") #debug
FIND_LIBRARY(MKL_LIBRARY mkl_rt
HINTS
$ENV{MKLROOT}
PATH_SUFFIXES
mkl
)

message("${MKL_LIBRARY}")
SET(MKL_FOUND FALSE)
IF(MKL_LIBRARY AND MKL_INCLUDE_DIR)
SET(MKL_FOUND TRUE)
ENDIF(MKL_LIBRARY AND MKL_INCLUDE_DIR)
IF( MKL_FOUND)
MESSAGE(STATUS "Found intel mkl")
MESSAGE(STATUS " ${MKL_LIBRARY}")
MESSAGE(STATUS " ${MKL_INCLUDE_DIR}")
ELSE ()
MESSAGE(STATUS "Could not find intel mkl")
ENDIF ()

